name: Feature request
description: Request a new feature or changed behavior
title: "[Feature]: "
labels: ["feature", "needs-spec", "enhancement"]
projects: ["Dynapro-AS/3"]
body:
  - type: textarea
    id: business-problem
    attributes:
      label: Business problem
    validations:
      required: true
  - type: textarea
    id: expected-outcome
    attributes:
      label: Expected outcome
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance criteria
      description: Use Given/When/Then if possible.
    validations:
      required: true
  - type: input
    id: business-central-task-id
    attributes:
      label: Business Central Task ID
      description: |
        Please enter the Business Central Task ID if applicable.
    validations:
      required: false
