---
name: Feature Request
description: Suggest an improvement or new feature
labels: ["enhancement"]
projects: ["Dynapro-AS/3"]
body:
  - type: textarea
    attributes:
      label: Description
      description: |
        A clear and concise description of the feature you're interested in.
      placeholder: |
        Describe your feature here...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposed Solution
      description: >
        Describe the solution you'd like. A clear and concise description of what you want to happen. If you have
        considered alternatives, please describe them.
      placeholder: |
        Describe your proposed solution here..
    validations:
      required: false

  - type: input
    id: business-central-task-id
    attributes:
      label: Business Central Task ID
      description: |
        Please enter the Business Central Task ID if applicable.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Screenshots? Links? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in. Or you can paste images directly into the text area.
    validations:
      required: false
